name: go-build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]

    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          mkdir -p release
          GOOS=${{ matrix.os }} GOARCH=arm64
          go build -o utils-${{ matrix.os }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: utils-${{ matrix.os }}
          path: utils-${{ matrix.os }}
